### ISSUE TITLE
The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by QIANGEGEGE** [dfinity/sdk#2501]
shell info:
[root@VM-20-7-centos ~]# sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
info: Executing dfx install script, commit: 809fab6d52fcf418536afe6c5e66a766e6c06c51
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:03:42 --:--:--     0
curl: (35) TCP connection reset by peer
info: Version found:
info: Creating uninstall script in ~/.cache/dfinity
info: uninstall path=/root/.cache/dfinity/uninstall.sh
info: Checking for latest release...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
dfinity-sdk: command failed: downloader https://github.com/dfinity/sdk/releases/download//dfx--x86_64-linux.tar.gz /tmp/tmp.2lZZmAVhuU/dfx--x86_64-linux.tar.gz
exit

**Comment by sesi200** [comment]
Is this happening regularly or just a one-off? We've had some hosting problems lately, but just 4 minutes after you submitted the issue I was not able to reproduce it. Can you try running it again?

**Comment by QIANGEGEGE** [comment]
@sesi200 Yesterday and today are the same, I tried on Alibaba Cloud and Tencent Cloud

**Comment by QIANGEGEGE** [comment]
i visit this url ： https://github.com/dfinity/sdk/releases/download//dfx--x86_64-linux.tar.gz        is 404

**Comment by sesi200** [comment]
Do you have `DFX_VERSION` set to empty string for some reason? Can you try to run `unset DFX_VERSION` and run it again? The URL the script tries to access is malformed, it should be `.../download/0.11.1/dfx--x86...` or some other version in between the slashes.

And if that doesn't help, you can try to manually set the version like this: `DFX_VERSION=0.11.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"`

**Comment by QIANGEGEGE** [comment]
thanks i try it

**Comment by QIANGEGEGE** [comment]
@sesi200   Thanks. This problem has been solved

**Comment by Jaseempk** [comment]
@sesi200 bro I'm still getting the same error even after doing what you have suggested,can
![Screenshot 2022-12-10 112303](https://user-images.githubusercontent.com/99121494/206831821-5b44dac4-d721-40d9-b968-ac4cea22fdbc.png)
 you please look into this?

**Comment by sesi200** [comment]
Your screenshot shows `Could not resolve host: objects.githubusercontent.com`. This is an issue with your network, not something we have control over
